create table if not exists entries (
  id bigint generated by default as identity primary key,
  name text not null,
  exercise text not null,
  count integer not null,
  created_at timestamptz default now()
);
